rime/weasel

- INSTALL.md
- build.bat
- env.bat.template
* Update submodules to latest commits to suit changes in NSIS scripts.
* Since `output/expansion` is now empty and no longer exists in the repo, the build script should automatically create one. I forgot this.
* Move `env.bat` to `env.bat.template` to prevent it from becoming dirty when building. Edit `INSTALL.md` to reflect the change.
* The console application is named `rime_api_console` instead of `rime_console`. Fixed a typo in `INSTALL.md`.
> Some minor adjustments.

- build.bat
Since Weasel's `build.bat` doesn't call librime's `build.bat boost` to build boost, boost dependencies must be fully built here.
> Fix boost dependencies in build.bat.

- README.md
轉換掉的話 GitHub 網頁上會更好看一點。轉換時考慮了作爲 txt 的可讀性，所以問題也不大，倒是可能需要在安裝器裏面加一些重命名的邏輯好讓用戶想到去點開。
順便還更新了 issue 報告鏈接。
感覺這個 PR 也該 Cherry-Pick 到別的 branch 上。
> README: 轉換到 Markdown 格式

- WeaselIPCServer/WeaselServerImpl.cpp
- WeaselIPCServer/WeaselServerImpl.h
fix #85 
用动态加载的方式避免在低版本报错。其他项目设置都复原了。
> fix dpi issue on high dpi display.

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselIPC/PipeChannel.cpp
- WeaselIPC/WeaselClientImpl.cpp
- WeaselIPC/WeaselClientImpl.h
- WeaselIPC/WeaselIPC.vcxproj
- WeaselIPC/WeaselIPC.vcxproj.filters
- WeaselIPCServer/SecurityAttribute.cpp
- WeaselIPCServer/SecurityAttribute.h
- WeaselIPCServer/WeaselIPCServer.vcxproj
- WeaselIPCServer/WeaselIPCServer.vcxproj.filters
- WeaselIPCServer/WeaselServerImpl.cpp
- WeaselIPCServer/WeaselServerImpl.h
- WeaselTSF/WeaselTSF.cpp
- include/PipeChannel.h
- include/RimeWithWeasel.h
- include/WeaselIPC.h
- test/TestWeaselIPC/TestWeaselIPC.cpp
- test/TestWeaselIPC/stdafx.h
- weasel.sln
- Extract pipe IPC from `ClientImpl` and `ServerImpl`
- Improve exception handling
Also as partial workaround for #110
> refactor(ipc): extract pipe channel and server

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselTSF/Composition.cpp
- include/WeaselUI.h
- output/data/weasel.yaml
- add config option `style/preedit_type(composition|preview)`
Set `style/preedit_type: preview` to display the first candidate as inline preedit.
> feat(tsf): support user defined preedit display type

- WeaselTSF/Composition.cpp
This should fix the crashes referred in #109.
Since all synchronous edit sessions are processed before any pending asynchronous edit sessions, use sync for `CEndCompositionEditSession` and `CStartCompositionEditSession` may cause unexpected early session closing resulting in crash.
Theoretically this change may lost synchronization of `WeaselTSF::_IsComposing` according to the [document](https://msdn.microsoft.com/en-us/library/windows/desktop/ms538796(v=vs.85).aspx), but I found it is used by the Microsoft Sample IME...
> fix(composition): fix crashes in notebook with inline preedit

- output/install.nsi
Besides the UI change, the installer now prompts reboot to ensure all processes that loaded Weasel once are terminated to avoid problems.
> feat(install.nsi): upgrade to Modern UI 2 and prompt reboot

- update/bump-version.sh
Example usage:
```sh
cd weasel
./update/bump-version.sh 0.9.30 minor  # => 0.10.0
```
Tested in macOS and msys bash.
> chore(script): bump version in source files and appcasts  [ci skip]

- WeaselTSF/KeyEventSink.cpp
Thank you for this great work!! We're happy we can contribute to weasel!
https://github.com/rime/weasel/issues/221#issuecomment-388056345
https://github.com/rime/weasel/issues/273
https://github.com/rime/weasel/issues/317
Type `123456789` in Word 2013, Win7
`123456789`
`123456789`
```
I0630 13:49:18.347062   308 engine.cc:99] process key: Shift+Shift_L
I0630 13:49:18.446949   308 engine.cc:99] process key: Shift+Release+Shift_L
I0630 13:49:18.446949   308 engine.cc:99] process key: Release+Shift_L
I0630 13:49:21.463521   308 engine.cc:99] process key: 1
I0630 13:49:21.883044   308 engine.cc:99] process key: Release+1
I0630 13:49:21.903021   308 engine.cc:99] process key: Release+1
I0630 13:49:21.903021   308 engine.cc:99] process key: 2
I0630 13:49:21.903021   308 engine.cc:99] process …
```
> Fixed half-width charactor disappeared in Word

- README.md
Bintray has been shutdown, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.
> Replace Bintray badge to GitHub releases

- WeaselIME/KeyEvent.cpp
- WeaselTSF/KeyEvent.cpp
在将ibus按键转义为Windows Virtual Keys时同时转义「变换」、「无变换」与「半角/全角」按键，使之在Windows中正常工作。
>  转义日文键盘中「变换」、「无变换」与「半角/全角」按键，使之在Windows中正常工作。

- build.bat
- output/install.nsi
使用librime 1.7.2 及build.bat变更：
`weasel\build.bat`在编译librime过程中`BOOST_ROOT`环境变量错误： librime1.7.2内`build.bat`会对[环境变量覆写] (https://github.com/rime/librime/blob/bcf811c37fed61ba9d5ee2317a36fccb78c3ddd4/build.bat#L8)  #608 
NSIS打包jnstaller会提示`*.ocd`文件不存在：新版本opencc输出文件后缀应为[`ocd2`](https://github.com/rime/weasel/issues/611#issuecomment-787005255)
测试环境[软件配置](https://github.com/crackself/weasel/blob/45f237f49b932874e745b9b56af0c6ce9c69342c/about_windows_compile.md)
> 使用librime1.7.2，build.bat脚本更新

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselServer/WeaselTrayIcon.cpp
- WeaselServer/WeaselTrayIcon.h
- WeaselTSF/LanguageBar.cpp
- WeaselTSF/LanguageBar.h
- WeaselUI/WeaselPanel.cpp
- WeaselUI/WeaselPanel.h
- include/WeaselCommon.h
和之前方案文件（或者custom文件）中可以通过```schema/icon```设定方案对应的中文icon类似，新增英文状态图标可自定义选项如下，注意的是目前这两个选项都只支持ico文件。
```yaml
schema/ascii_icon: ascii_icon_file.ico
```
示例效果（这里有带style/display_tray_icon: true ,实际建议这个关闭，直接使用语言栏）
> 特性：支持方案自定义英文状态icon

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselTSF/Composition.cpp
- include/WeaselCommon.h
1. 光标跟随改善：改善部分获取光标位置失败导致光标位置在屏幕左上角的问题，异常时光标位移到窗口左上角位置。
光标位置问题改善例子，fontforge（应用原因，微软拼音也无法准确获取光标位置）
> Enhance position

- WeaselUI/WeaselPanel.cpp
- WeaselUI/WeaselPanel.h
- WeaselUI/WeaselUI.cpp
1. 减少不必要的重绘（由UI::UpdateInputPosition触发引起），减少一次击键触发的重绘的次数，从而提升整体绘制的效率，响应更快。
2. 空指针异常调用处理，避免在composing途中通过ctrl+空格来禁用输入法后键入退格引起的应用崩溃问题。
> Enhance drawing performance

- WeaselTSF/DisplayAttributeInfo.cpp
#893 提到的问题
修改DisplayAttributes属性为不修改字体和下划线颜色，交由应用自行决定
> 修复inline_preedit模式下，preedit字体与下划线颜色问题

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselUI/WeaselPanel.cpp
- WeaselUI/WeaselPanel.h
- include/WeaselUI.h
1. 修復vertical_auto_reverse狀態下部分狀態不能正常顯示候選的問題
2. 修復vertical_auto_reverse狀態，天圓地方的圓角狀態不正確的問題
3. 增加特性： 支持方案內設定（weasel.yaml中定義的）配色
> 修復vertical_auto_reverse顯示異常,支持方案內設定配色

- WeaselServer/WeaselTrayIcon.cpp
- WeaselUI/fontClasses.cpp
1. 修复字体设定的start_code_point/end_code_point 只使用a-f组成时，对应的range解析不正确的问题。
2. 修复语言栏菜单通过鼠标点击部署时无显示装载中的图标的问题
> fixed: font parsing bug when code point value with non-digit characte

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselUI/HorizontalLayout.cpp
- WeaselUI/WeaselPanel.cpp
- WeaselUI/fontClasses.cpp
- include/WeaselCommon.h
- output/data/weasel.yaml
fix bug issue #908 
style/layout/min_width not work for horizontal layout.
feature: antialias mode optional
`style/antialias_mode: "default" | "cleartype" | "grayscale" | "aliased" | "force_dword" `
> fixed: style/layout/min_width not work for horizontal layout.

- .github/workflows/commit-ci.yml
- .github/workflows/release-ci.yml
- .gitignore
- build.bat
- 更改编译平台为 windows-2022
- 更改了 boost 的编译参数，并提升了目标操作系统版本至 Win 8.1
- 开启 boost 的并行编译
- **WeaselSetup 反而报毒变多，需要修改一下**（工具链换到 2022 后报毒就变多了）
对比：
| File | Proposed PR | https://github.com/rime/weasel/commit/e2679946367c8d780af64454591e8f889276af44 |
|--|--|--|
|WeaselServer.exe|3/70|13/68|
|WeaselDeployer.exe|3/69|1/71|
|WeaselSetup.exe|14/71|3/68|
|weasel.dll|0/70|0/70|
virustotal 链接：
https://www.virustotal.com/gui/file/4463d051c99121c0b38896e7b82b74b3372ccb471f85c0a87132811c2f3aa451?nocache=1
https://www.virustotal.com/gui/file/4313060c91dcbc26ed2b0505a82e766ab91260d69210b3d577f5ff9ece0dfe62?nocache=1
https://www.virustotal.com/gui/file/b8bd3f55fce06db3a7d5012697cd831cccb992ee6a85a5976728ac865572a91b?nocache=1
https://www.virustotal.com/gui/file/bc48ef17233e9b240444a3132ecb3b327c45a1c464711adb4475 …
> 病毒误报改进 [skip ci]

- WeaselTSF/Composition.cpp
> 修复候选框随文字移动问题

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselSetup/WeaselSetup.cpp
- WeaselSetup/WeaselSetup.vcxproj
- WeaselTSF/Register.cpp
- WeaselTSF/WeaselTSF.cpp
- WeaselUI/WeaselPanel.cpp
- include/WeaselCommon.h
- output/data/weasel.yaml
* fixed: weasel not work with wezterm in gpu mode.  #863 , maybe more.
* ui enhancement: WeaselSetup dpi per monitor aware.
* ui enhancement: x position more close to input pos when vertical text right to left with shadow_offset_x negative value.
* feat: new bool type parameter `style/ascii_tip_follow_cursor: bool`, allow to configure if ascii tip follow mouse cursor
thanks great helps by @Techince
> 修复wezterm无法输入的问题

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselServer/WeaselServer.cpp
- WeaselUI/WeaselPanel.cpp
- WeaselUI/WeaselPanel.h
1. 修复 #913 中提及的firefox问题
2. 通过named mutex实现单实例运行，潜在可能解决#926 中双启动项引起的自启失败问题
3. 预防主要文字透明异常发生 在 #730 中提及的候选文字透明问题
> UI bug修复，单实例运行，防止主要文字透明

- RimeWithWeasel/RimeWithWeasel.cpp
> fixed: _RimeParseStringOptWithFallback output value error, when load settings from schema. rime#976

- WeaselUI/WeaselPanel.cpp
如题，修复新增的高亮标识状态(hilited_mark_color非透明 && mark_text为空）被hilited_candidate_back_color遮盖的问题
测试确认图如下
> fixed: hilited mark covered by hilited_candidate_back_color, when mark_text empty and hilited_mark_color not transparent

- WeaselTSF/CandidateList.cpp
> fixed: click selecting does not work properly with word.

- include/PipeChannel.h
enable longer content transaction, longer candidates' info
> increase PipeChannel bs default value up to 64kB

- RimeWithWeasel/RimeWithWeasel.cpp
feat: style/text_orientation: {string: horizontal or vertical} as alias of style/vertical_text: {false or true}, to determine if to use vertical text layout. make it compatible with squirrel setting
> feat: style/text_orientation: {string: horizontal or vertical}

- RimeWithWeasel/RimeWithWeasel.cpp
- include/RimeWithWeasel.h
- output/data/weasel.yaml
by this pr,  we can determine when to show notifications, except deployment's.
for example, set `show_notifications_when: never` could disable all notifications except msg from deployment.
```yaml
#in weasel.yaml
show_notifications_when: always
```
> feat: add option shown_notifications_when: {string}, to determine when to show notifications

- .github/workflows/commit-ci.yml
- .github/workflows/release-ci.yml
- RimeWithWeasel/RimeWithWeasel.cpp
fix #1035 
and add error detection in ci workflow.
> fix c1f24cf. and add error detection in ci workflow.

- RimeWithWeasel/RimeWithWeasel.cpp
fix #1041 
chore: Update inline preedit option only when inline_preedit is changed
> fixed: inline_preedit not work properly when switching between apps, if inline_preedit is set in app_options

- .github/workflows/release-ci.yml
> nightly build

- RimeWithWeasel/RimeWithWeasel.cpp
`Esc`, `<C-[>`, `<C-c>`, `<C-C>` to set ascii mode true, just like what squirrel does.
fix #713
> feat: vim_mode in app_options

- RimeWithWeasel/RimeWithWeasel.cpp
- include/RimeWithWeasel.h
> app name case insensitive in app_options

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselIPCServer/WeaselServerImpl.cpp
- WeaselIPCServer/WeaselServerImpl.h
- include/RimeWithWeasel.h
- include/WeaselIPC.h
- include/WeaselUtility.h
`style/color_scheme_dark: {string}`,  auto light/dark mode switching for windows 10 1809+
it can be set in schema too
> color_scheme_dark for Windows 10 1809+

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselUI/DirectWriteResources.cpp
- WeaselUI/FullScreenLayout.cpp
- WeaselUI/HorizontalLayout.cpp
- WeaselUI/Layout.h
- WeaselUI/StandardLayout.cpp
- WeaselUI/StandardLayout.h
- WeaselUI/VHorizontalLayout.cpp
- WeaselUI/VerticalLayout.cpp
- WeaselUI/WeaselPanel.cpp
- WeaselUI/WeaselPanel.h
- WeaselUI/WeaselUI.cpp
- include/WeaselCommon.h
- include/WeaselUI.h
- output/data/weasel.yaml
- chore: string type option parsing code rewrite
- fix: typo in WeaselCommon.h
- feat: `style/candidate_abbreviate_length: {int}` to make long candidate abbreviation
- feat: `style/click_to_capture: {bool}`  to determine if to use `click_to_capture` feature
- perf: rewrite layered window redrawing, less redraw esp when candidate window moving.
- fix: attemt to fix empty candidate text issue. #994
known issue: with this pr, situation that couldn't work properly in some app not solved.
make long candidate abbreviated in candidate window, with configuration 
```yaml
style/candidate_abbreviate_length: 30
```
> UI performance, some fix and features

- WeaselUI/WeaselPanel.cpp
fix: hilited back 1 px out of back, when hilite_padding equal margin and border equal 0.  fix #1056
> fix: hilited back 1 px out of back, when hilite_padding equal to margin and border equal to 0

- output/install.nsi
close #949 
- 为卸载旧版本的提示语添加了多语言支持
- 修复静默安装的问题，使用 `/S` 可以执行静默安装
关联 https://github.com/microsoft/winget-pkgs/pull/116453
> silent installation fix

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselUI/WeaselPanel.cpp
- include/WeaselCommon.h
tips of all options except ascii_mode, will  be the state labels specificed in schema switches
fixed: #1076
> feat: full_shape, ascii_punct, simplification tip by option state_label

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselTSF/Compartment.cpp
fix: ascii mode is reset, when adding session, with global_ascii enabled: reuse the previour ascii_mode;
fix: ascii mode is reset, when reopen keyboard (e.g. by Ctrl+Space, or Backspace/Space with keyboard open in Gvim), code lines from #856 . fix #567 #581 
feat: clear composition when close keyboard
> global ascii fix 

- WeaselServer/WeaselServer.cpp
- WeaselTSF/LanguageBar.cpp
relative PRs
#956 
#945 
relative issue
#926 
with this PR merged,  restart WeaselServer.exe by calling `WeaselServer.exe` back and ensure
> fix: could not restart server by calling `WeaselServer.exe`

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselServer/WeaselServer.cpp
switch ascii mode of active session, if `global_ascii` set false
or switch ascii mode of all sessions, if `global_ascii` set true
from command line with `WeaselServer.exe /ascii` or `WeaselServer.exe /nascii`
> feat: switch ascii mode by command line

- output/data/weasel.yaml
> fix: Unable to input in Firefox settings interface (workaroud by set inline_preedit) [skip ci]

- WeaselUI/StandardLayout.cpp
when vertical_text enable, inline_preedit: false, style/vertical_text_left_to_right: true and not candidates.
> fix: round info for hilite text not correct

- WeaselServer/WeaselTrayIcon.cpp
if locale traditional chinese 
else
> chore: fix ShowBalloon tip translation follow locale

- WeaselUI/WeaselPanel.cpp
> chore: WeaselUI, mark bar not larger than 0.618*backsize(height/width)

- .github/workflows/commit-ci.yml
- .github/workflows/release-ci.yml
in recent pr build I found that `build.bat` reported errors and they were ignored by the ci script.
`build.bat` checks error after every step, but the ci script doesn't.
also removed commented out code.
> ci: call build.bat once to fail ci on build error

- WeaselTSF/ThreadMgrEventSink.cpp
e.g., esp situation is that in Setting App of Windows, composing and click outside and back.
> fix: composition not aborted when WeaselTSF::OnSetFocus(ITfDocumentMgr* pDocMgrFocus, ITfDocumentMgr* pDocMgrPrevFocus) called to HideUI

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselUI/DirectWriteResources.cpp
- WeaselUI/WeaselPanel.cpp
- include/WeaselCommon.h
- output/data/weasel.yaml
add param: `style/layout/baseline: {int}` and `style/layout/linespacing: {int}`, chance to avoid candidate height/width flickering by adjudging baseline position and linespacing (percentage of font point). default both `0 to disable adjudging`.
fixed: #1175
fixed: #866
patch file example
```yaml
patch:
style/layout/baseline: 100  # 100% of font point height
style/layout/linespacing: 140   # 140% of font point height, when flicker happened, should be a value larger than 100
```
> add parameter for chance to avoid linespacing flickering

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselUI/FullScreenLayout.cpp
- WeaselUI/HorizontalLayout.cpp
- WeaselUI/Layout.h
- WeaselUI/VHorizontalLayout.cpp
- WeaselUI/VerticalLayout.cpp
- WeaselUI/WeaselPanel.cpp
- WeaselUI/WeaselPanel.h
- include/WeaselCommon.h
- refactor: drop `style/mouse_hover_ms`, `style/hover_type: {none|semi_hilite|hilite}` to determine hover type, performance enhanced.
- feat: highlight bar and highlight shadow reaction when clicked down;
- fix: mark bar round corner not a fixed 2 pixel
- mark bar weight by 1/7 of height of size of character "|"
close #1156 
`style/hover_type: none`
`style/hover_type: hilite`
`style/hover_type: semi_hilite`
> enhance mouse reactions

- WeaselTSF/ThreadMgrEventSink.cpp
Reverts rime/weasel#1182
close #1178
> Revert "fix: composition not aborted when WeaselTSF::OnSetFocus(ITfDocumentMgr* pDocMgrFocus, ITfDocumentMgr* pDocMgrPrevFocus) called to HideUI"

- RimeWithWeasel/RimeWithWeasel.cpp
- RimeWithWeasel/RimeWithWeasel.vcxproj
- RimeWithWeasel/WeaselUtility.cpp
- WeaselDeployer/Configurator.cpp
- WeaselDeployer/SwitcherSettingsDialog.cpp
- WeaselDeployer/WeaselDeployer.vcxproj
- WeaselIME/WeaselIME.vcxproj
- WeaselIPC/WeaselIPC.vcxproj
- WeaselIPCServer/WeaselIPCServer.vcxproj
- WeaselServer/WeaselServer.vcxproj
- WeaselServer/WeaselServerApp.cpp
- WeaselServer/WeaselServerApp.h
- WeaselSetup/WeaselSetup.vcxproj
- WeaselSetup/imesetup.cpp
- WeaselTSF/LanguageBar.cpp
- WeaselTSF/WeaselTSF.vcxproj
- WeaselUI/WeaselUI.vcxproj
- include/WeaselUtility.h
- test/TestResponseParser/TestResponseParser.vcxproj
- test/TestWeaselIPC/TestWeaselIPC.vcxproj
通常退出服务是为了进行一些修改，此时无法快速打开 **程序文件夹** 十分不便
并且之前的方式，由于可能造成 **Explorer 无响应** 90ea523b6598310a8fcb2651361d8810ea22c358
而改为了启动一个新的 **Explorer 进程** 来打开文件夹，导致出现大量 Explorer进程
而分别由Server 和 TSF 打开文件夹，则不会出现 Explorer 无响应，所以可以不用启动大量的 Explorer 进程，并且打开窗口可以立刻出现在前台，更为方便
优化后，只有一个进程：
> 优化体验，服务退出后，仍然可以通过右键打开 用户/程序文件夹，同时避免启动大量 Explorer 进程

- WeaselTSF/EditSession.cpp
> fix: input position flicker when wrap in Word line ending

- WeaselServer/WeaselServerApp.cpp
- WeaselServer/WeaselTrayIcon.cpp
在 display_tray_icon 设置为true的情况下，服务重启成功后，图标并不会立刻出现，给人没有启动的错觉，效果如下
**修复前**
**修复后**
> 解决重启服务后，Tray Icon 不能立刻出现的问题

- WeaselTSF/Composition.cpp
- WeaselTSF/KeyEventSink.cpp
- WeaselTSF/WeaselTSF.h
- WeaselUI/WeaselPanel.cpp
close #1017
key change: 
1) check if hr == TF_S_ASYNC after _UpdateComposition
2) TF_ES_ASYNCDONTCARE when RequestEditSession
3) check if _async_edit true when OnKeyUp, not to _UpdateComposition when _async_edit true.
known issue:
1) sometimes, couldn't select candidate by space but by number
> fix: async editing flicker, esp example in Word 365[wip]

- WeaselUI/DirectWriteResources.cpp
- WeaselUI/HorizontalLayout.cpp
- WeaselUI/VHorizontalLayout.cpp
- WeaselUI/VerticalLayout.cpp
- fix: min_height does not work properly when vertical text layout
- fix: `style/layout/baseline` and  `style/layout/linespacing` do not work properly when vertical text layout
- fix: min_height and min_width do not work properly when predicted
> fix layout bugs with params min_height/min_width/linespacing/baseline

- WeaselTSF/WeaselTSF.cpp
- WeaselTSF/WeaselTSF.h
- WeaselUI/FullScreenLayout.cpp
- WeaselUI/HorizontalLayout.cpp
- WeaselUI/VHorizontalLayout.cpp
- WeaselUI/VerticalLayout.cpp
- WeaselUI/WeaselUI.cpp
- include/WeaselIPCData.h
- update language bar icon with ITfThreadFocusSink
- filter unnecessary UI  updates, avoiding segfault triggered by frequently update ui in WeaselServer. 
about the segfault, if ui not fixed, it might trigger directwrite nullptr referenced(in RimeWithWeasel ),  when quickly and repeatedly switch between two apps
> fix: language bar icon not updated when thread changed (esp work with global_ascii set )

- WeaselTSF/CandidateList.cpp
- WeaselTSF/CandidateList.h
- WeaselTSF/WeaselTSF.cpp
keep  directwrite resources alive when TSF status activated, less object re-creations.
> perf: only clean directwrite resources when TSF Deactivate called.

- .github/workflows/release-ci.yml
> ci: bump action-gh-release to v2

- RimeWithWeasel/RimeWithWeasel.cpp
- WeaselTSF/WeaselTSF.cpp
- Don't call m_ui->Update in RimeWithWeasel.cpp when tsf session, don't call _RefreshTrayIcon when `display_tray_icon` false.
call m_ui->Update unless it's not tsf session (less UI updating in Server), attempt to avoid crash caused by unnecessary UI updating.
- remove unnecessary UI update trigger by WeaselTSF::OnSetThreadFocus
> Less UI updating in WeaselServer

- WeaselUI/WeaselPanel.cpp
> fix: candidate window performance becomes bad when typing in 2nd high resolution monitor with higher dpi.

- .github/workflows/commit-ci.yml
- .github/workflows/release-ci.yml
- build.bat
Reverts rime/weasel#1266
rime.dll can not work properly with `preedit_format` #1268, so now it's not good time to provide `rime.pdb`
fix #1268
> Revert "build: update build.bat on building rime, build/cache librime in CI, and provide rime.pdb"

- WeaselTSF/KeyEventSink.cpp
attempt to fix #1162, fix #997
> attempt to fix key event issue in Chrome under Windows 11

- output/install.nsi
if run installer with `/S`, `CheckForUpdates` disabled.
close #1295
> installer: msgbox to enable or disable CheckForUpdates

- WeaselDeployer/WeaselDeployer.cpp
- WeaselServer/WeaselServer.cpp
- WeaselSetup/WeaselSetup.cpp
- WeaselTSF/LanguageBar.cpp
- include/WeaselUtility.h
> fix: the UI language was incorrectly determined by "Region Format"

- WeaselIPC/ContextUpdater.cpp
- WeaselIPC/Deserializer.h
- WeaselIPC/Styler.cpp
esp when newer server to work with old ime/dll
> fix: if IPC serialization exception happens, client app would crash cause no exception handler provided.

- output/install.nsi
Display the software’s own icon in the uninstall entry in `Control Panel\Programs\Programs and Features` instead of the boring system icon.
> installer: uninstall key add `DisplayIcon`

- WeaselTSF/Composition.cpp
- WeaselTSF/EditSession.cpp
- WeaselTSF/KeyEventSink.cpp
- WeaselTSF/WeaselTSF.h
- ability to use  `Caps_Lock` in `key_binder/bindings`
example to binding `Caps_Lock` to `4` when `has_menu`, to select the 4th candidate
```yaml
patch:
engine/processors/@before 0: key_binder
key_binder/bindings/+:
- { accept: Caps_Lock, send: 4, when: has_menu} 
- { accept: Release+Caps_Lock, send: Release+4, when: has_menu}
```
> feat: Caps_Lock binding available

- WeaselIPC/WeaselClientImpl.cpp
> fix: unexpected windows error event after closing mmc.exe or WINWORD.EXE

- .github/workflows/commit-ci.yml
as llvm-18.1.8 has been installed in Windows-2019，check clang-format version ≥ 18.1.6 by powershell commands and install llvm 18.1.6 if necessary, instead of actions/cache.
> ci: install llvm if necessary by pwsh commands, instead of actions/cache

- WeaselIPC/WeaselClientImpl.cpp
since 0.16.0, we add async task for _SendMessage to attempt to fix freeze issues, however it seems not always OK, so let's reverse it.
maybe fix #1341 
relative issue #1286
> reverse async in IPC send message

- .github/workflows/commit-ci.yml
- RimeWithWeasel/xmake.lua
- WeaselDeployer/xmake.lua
- WeaselIME/xmake.lua
- WeaselIPC/xmake.lua
- WeaselIPCServer/xmake.lua
- WeaselServer/xmake.lua
- WeaselSetup/xmake.lua
- WeaselTSF/xmake.lua
- WeaselUI/xmake.lua
- install-clang-format.bat
- test/TestResponseParser/xmake.lua
- test/TestWeaselIPC/xmake.lua
- xbuild.bat
- xmake.lua
xmake optional with xbuild.bat, xmake **2.9.4** is required 
build.bat compatible parameters:
- `release`, `debug`
- `rebuild`
- `boost`
- `data`
- `opencc`
- `rime`, `librime`
- `weasel`
- `installer`
- `arm64`
- `all`
new parameters:
- `clean`     to  clean build cache 
- `commands`  to generate compile_commands.json
> build: xmake optional

- WeaselSetup/WeaselSetup.cpp
- WeaselTSF/Compartment.cpp
- WeaselTSF/KeyEventSink.cpp
- WeaselTSF/LanguageBar.h
- WeaselTSF/WeaselTSF.cpp
- WeaselTSF/WeaselTSF.h
- WeaselTSF default toggle ascii_mode on keyboard open/close messages(esp., Ctrl+Space), if `HKEY_CURRENT_USER\SOFTWARE\Rime\Weasel\ToggleImeOnOpenClose` is not set `yes`
- WeaselSetup parameters, `/toggleime` to enable toggle ime on keyboard open/close message, `/toggleascii` to toggle ascii_mode when those messages come.
fixed: #1343 
possible issues:
#997 might be reopen
> feat: GUID_COMPARTMENT_KEYBOARD_OPENCLOSE actions configurable.

- WeaselSetup/WeaselSetup.cpp
- WeaselSetup/WeaselSetup.vcxproj
- WeaselSetup/xmake.lua
- 写 HKCU 的命令不需要管理员权限，工程文件里的 RequireAdministrator 改为 AsInvoker
- 调用 uninstall 和 install/CustomInstall 前判断一下进程的状态， 如果不是管理就提权重启
> feat: 默认启动不请求管理员权限，必要时使用管理员权限重启

- RimeWithWeasel/RimeWithWeasel.vcxproj
- WeaselDeployer/WeaselDeployer.vcxproj
- WeaselIME/WeaselIME.vcxproj
- WeaselIPC/WeaselIPC.vcxproj
- WeaselIPCServer/WeaselIPCServer.vcxproj
- WeaselServer/WeaselServer.vcxproj
- WeaselSetup/WeaselSetup.vcxproj
- WeaselTSF/WeaselTSF.vcxproj
- WeaselUI/WeaselUI.vcxproj
- test/TestResponseParser/TestResponseParser.vcxproj
- test/TestWeaselIPC/TestWeaselIPC.vcxproj
make `$(SolutionDir)\msbuild` as the intermediary path, keep file directory clean and clear, easier to clean intermediary files
> build: IntDir and OutDir set for msbuild solution, intermediary files will be always in `$(SolutionDir)\msbuild`.

- WeaselSetup/WeaselSetup.cpp
example 
```bat
WeaselSetup.exe /userdir:D:\rimedata
```
> feat: WeaselSetup.exe parameter /userdir:<user_data_dir_full_path> to set user data directory in command line

- WeaselUI/WeaselPanel.cpp
- include/WeaselUI.h
after GPU reset ( situation of driver reinstalling, wakeup ETC.  ), the render target object will be invalid.
reset direct2d resources if `EndDraw()` failed, then refresh the ui.
Tested by powershell script( run as admin)
```powershell
Set-ExecutionPolicy RemoteSigned -Scope Process
$gpu = Get-PnpDevice -Class Display | Where-Object { $_.Status -eq 'OK' }
if ($gpu) {
Disable-PnpDevice -InstanceId $gpu.InstanceId -Confirm:$false
Start-Sleep -Seconds 2
Enable-PnpDevice -InstanceId $gpu.InstanceId -Confirm:$false
Write-Host "显卡驱动已成功重新加载。"
} else {
Write-Host "未找到有效的显卡设备。"
}
```
> fix: candidate ui can't be drawn correctly after GPU reset

- output/install.nsi
+2: 跳过当前指令和下一条指令
fixes: https://github.com/rime/weasel/commit/8e6b477ea6daec22606f7d42fd4faf67d13a2f65
> fix: silent installation script typo

- WeaselUI/FullScreenLayout.cpp
> fix(WeaselUI): highlight back is not drawn correctly when fullscreen layout set

- weasel.props.template
set `/utf-8` option for all msvc projects, fix charset warning when compiling
> build: set /utf-8 for source compilation

- RimeWithWeasel/RimeWithWeasel.cpp
> fix(RimeWithWeasel): blend_colors algorithm, fix issue like rime#1405

- .github/workflows/commit-ci.yml
- .github/workflows/release-ci.yml
- get-rime.ps1
- github.install.bat
chore: add tool script  for updating librime lib from upstream
> build: bump librime to 1.13.0

- WeaselUI/WeaselPanel.cpp
- WeaselUI/WeaselPanel.h
fix #1445
fix #1464
感谢 @nicangtianws 提供了一个轻巧且稳定可复现的软件 SimpleStickyNotes。
问题很简单，某些软件并不依赖 WM_PAINT 消息来重绘，甚至直接在消息循环中吃掉了 WM_PAINT 消息，候选框重绘又依赖 WM_PAINT 消息，所以候选框就显示不出来。
解决办法就是手动重绘，不依赖 WM_PAINT 消息。
> fix(CandidateList): not displaying in some applications

- clang-format.ps1
tested in Ubuntu 22.04 (WSL) with Powershell 7.4.7
> chore: make clang-format.ps1 worked in linux/Mac OS[skip ci]

- WeaselTSF/Compartment.cpp
- WeaselTSF/LanguageBar.cpp
fix #1486
现在能正确响应 `ImmSetOpenStatus` 和 `ImmSetConversionStatus`，也能正确支持 ImTip，但是依然发现以下问题：
1. WeaselServer.exe 管理下的托盘图标和悬浮状态图标更新有问题，看了眼 RimeWithWeasel 的实现。。呃，我放弃了。。耦合太强了。
2. 对于 keyboard open，微软拼音是在获得焦点时无脑 open 并切换为中文输入，但是这样就与 `ImmSetConversionStatus` 冲突，调用输入法的程序无法通过 api 切换为英文输入，想了想还是不跟了，影响太大。
> fix(tsf): ime status

- .github/workflows/release-ci.yml
- .github/workflows/update-appcast.yml
don't update appcast on rime/home in release-ci.yaml workflow, but on published (draft release published) or prereleased (nightly)
> ci: run update rime/home appcast on published or prereleased

- output/install.nsi
NSIS about `/REBOOTOK`
https://nsis.sourceforge.io/Reference/Delete#:~:text=If%20%2FREBOOTOK%20is%20specified%20and%20the%20file%20cannot,a%20reboot%2C%20the%20reboot%20flag%20will%20be%20set.
fix: #1514 
fix: #1496
> fix(installer): avoid files are deleted on system reboot when weasel is reinstalled in the same WeaselRoot

- WeaselUI/DirectWriteResources.cpp
- WeaselUI/Layout.h
- WeaselUI/StandardLayout.cpp
- WeaselUI/StandardLayout.h
- WeaselUI/WeaselPanel.cpp
- include/WeaselUI.h
- include/WeaselUtility.h
- refactor: simplify some operation on direct2d/directwrite
- fix(WeaselUI): hemispherical of hilite text preedit not correct
> Refs/heads/refactor UI

- update/bump-version.ps1
- update/bump-version.sh
prepare txt file of new tag name like 0.16.3.txt, which contains extra changelog information to insert
> chore: update bump version scripts

- RimeWithWeasel/RimeWithWeasel.cpp
fix(RimeWithWeasel): highlight label color and highlight comment color not correct when it's not defined
fix: #1582
> fix(RimeWithWeasel): color parsing for decimal number

- WeaselTSF/Compartment.cpp
- WeaselTSF/LanguageBar.cpp
Reverts rime/weasel#1499
Conflicts with librime's `ascii_mode` feature. (#1564)
> Revert "fix(tsf): ime status"

- .github/workflows/commit-ci.yml
- .github/workflows/release-ci.yml
- arm64x_wrapper/build.bat
- build.bat
- xbuild.bat
- fix lint caused by runner updating
- workaround to pass ci by setting sdk version
> ci: fix ci actions caused by runner updating
