RimeWithWeasel/RimeWithWeasel.cpp, WeaselUI/HorizontalLayout.cpp, WeaselUI/Layout.h, WeaselUI/StandardLayout.cpp, WeaselUI/StandardLayout.h, WeaselUI/VerticalLayout.cpp, WeaselUI/WeaselPanel.cpp, WeaselUI/stdafx.h, include/WeaselCommon.h
Reference: 
* [rime/librime#57] (https://github.com/rime/librime/issues/57)
* [rime/ibus-rime@`6b659b0`] (https://github.com/rime/ibus-rime/commit/6b659b0c6220ec5cec47e27c5a849462df9e0445)
=> Enable custom labels with menu/alternative_select_labels.

INSTALL.md, PyWeasel/PyWeasel.vcxproj, RimeWithWeasel/RimeWithWeasel.vcxproj, WeaselDeployer/WeaselDeployer.vcxproj, WeaselIME/WeaselIME.vcxproj, WeaselIPC/WeaselIPC.vcxproj, WeaselIPCServer/WeaselIPCServer.vcxproj, WeaselServer/WeaselServer.vcxproj, WeaselSetup/WeaselSetup.vcxproj, WeaselTSF/WeaselTSF.vcxproj, WeaselUI/WeaselUI.vcxproj, build.bat, output/install.nsi, shell.bat, test/TestPyWeasel/TestPyWeasel.vcxproj, test/TestResponseParser/TestResponseParser.vcxproj, test/TestWeaselIPC/TestWeaselIPC.vcxproj, weasel.sln
* Now Weasel can be built with single execution of `shell.bat` and `build.bat`.
* Remove `libglog.dll` from NSIS script since glog is statically linked.
=> Update build scripts and NSIS script for Visual Studio 2015.

appveyor.after_build.bat, appveyor.install.bat, appveyor.yml, build.bat, weasel-appveyor.props
This script
* Makes use of AppVeyor CI artifacts of librime.
* Generates installer packages as artifacts.
=> Implement AppVeyor CI automated build script.

RimeWithWeasel/RimeWithWeasel.cpp, WeaselUI/HorizontalLayout.cpp, WeaselUI/Layout.h, WeaselUI/StandardLayout.cpp, WeaselUI/StandardLayout.h, WeaselUI/VerticalLayout.cpp, WeaselUI/WeaselPanel.cpp, include/WeaselUI.h, output/data/weasel.yaml
Label text format can be customized with `style/label_format` attribute.
=> feat(config): enable customization of label format

WeaselIPCServer/SecurityAttribute.cpp, WeaselIPCServer/SecurityAttribute.h, WeaselIPCServer/WeaselServerImpl.cpp
=> fix(ipc): grant access to IE protected mode

WeaselTSF/Composition.cpp, WeaselTSF/EditSession.cpp, WeaselTSF/TextEditSink.cpp, WeaselTSF/WeaselTSF.h
=> fix(composition): improve compositions and edit sessions

RimeWithWeasel/RimeWithWeasel.cpp, WeaselTSF/Composition.cpp
=> fix(session): close edit session when unfocus

WeaselIPCServer/WeaselServerImpl.cpp, include/WeaselIPC.h, include/WeaselUtility.h
=> fix(server): use kernel mutex to ensure single instance

WeaselTSF/CandidateList.cpp, WeaselTSF/CandidateList.h, WeaselTSF/Composition.cpp, WeaselTSF/EditSession.cpp, WeaselTSF/WeaselTSF.h, WeaselUI/WeaselPanel.cpp, WeaselUI/WeaselUI.cpp
=>  fix(tsf): create candidate window for each composition separately 

WeaselTSF/CandidateList.cpp, WeaselTSF/CandidateList.h, WeaselTSF/Compartment.cpp, WeaselTSF/ThreadMgrEventSink.cpp, WeaselTSF/WeaselTSF.h
=>  fix(tsf): hide candidate window when set focus on different document 

WeaselTSF/KeyEvent.cpp
=> fix(tsf): differentiate between keyboard and numpad enter keys

WeaselTSF/Register.cpp
To keep windows reg clean. `UnregisterProfiles()` unregisters all registered in `RegisterProfiles()`
`UnregisterProfiles()` follows the structure of `RegisterProfiles()`,  separating win-7 and newer version.
This code are tested by reinstalling twice, in win7 and win10.
=> Unregister what was registered.

.github/workflows/windows-build.yml
压缩并上传 CI 构建的调试符号，允许开发者和用户在遇到问题时进行调试。
=> CI Feature: 压缩并上传 CI 构建的调试符号

.github/workflows/commit-ci.yml, .github/workflows/release-ci.yml, github.install.bat, install_boost.bat
update librime to version 1.9.0, update boost version to 1.83.0 like librime 1.9.0
=> update to librime 1.9.0

WeaselUI/StandardLayout.cpp
fix: trailing white space ignored when layout.
=> fix trailing white space

WeaselUI/WeaselPanel.cpp
fix aliasing of hilite mark text, caused by drawing incorrectly.
=> fix aliasing of hilite mark text

WeaselTSF/Composition.cpp
fix word issue mentioned in #1024
=> fixed: candidate window not shown right after keydown, in some apps like excel

WeaselUI/FullScreenLayout.cpp, WeaselUI/HorizontalLayout.cpp, WeaselUI/VHorizontalLayout.cpp, WeaselUI/VerticalLayout.cpp, WeaselUI/WeaselPanel.cpp
decrease unnecessarily pixel gap between highlighted mark and label
=> chore: hilited mark gap and width pixel modification

.github/workflows/commit-ci.yml, .github/workflows/release-ci.yml, github.install.bat
- cache librime when submodule, update release-ci.yml and commit-ci.yml
- librime to 1.10.0
- plum to master HEAD
- update actions version and setup-msbuild version
=> cache librime

github.install.bat
possible relative issues #1109 #1116 #1160
=> bump librime to 1.11.0

build.bat
=> fix: rime-install-config.bat not updated when build.bat data

RimeWithWeasel/RimeWithWeasel.cpp, WeaselIPC/Committer.cpp, WeaselIPC/ContextUpdater.cpp, include/WeaselUtility.h
escape LF to "\\\\n" to avoid crash cause by LF in context
=> Escape LF[wip]

output/install.nsi
maybe 
fix: #1190  #1173 
tool to check autorun when system startup
https://learn.microsoft.com/zh-cn/sysinternals/downloads/autoruns
=> install: don't redirect for autorun setting on 64 bit system

weasel.props.template
however you need to set `env.bat` and run `build.bat` first to generate `weasel.props`
=> fix: weasel.props.template does not works for visual studio IDE build

WeaselSetup/imesetup.cpp
=> fix: weasel is not added or remove in control panel, when installed/uninstalled

WeaselDeployer/DictManagementDialog.cpp
and remember to CoUninitialize
=> make_preferred instead of regex_replace when handling path

WeaselIPC/ContextUpdater.cpp
=> fix: caret sometimes is not correct when inline_preedit

WeaselSetup/WeaselSetup.vcxproj, WeaselTSF/CandidateList.cpp, WeaselTSF/Composition.cpp, WeaselTSF/KeyEventSink.cpp, WeaselUI/DirectWriteResources.cpp, WeaselUI/FullScreenLayout.cpp, WeaselUI/Layout.cpp, WeaselUI/StandardLayout.cpp, WeaselUI/VHorizontalLayout.cpp, WeaselUI/WeaselPanel.cpp, WeaselUI/WeaselUI.cpp
handle some type casting warning issues
=> Dewarnings

README.md
=> chore: update readme [skip ci]

WeaselSetup/imesetup.cpp
introdced by a4d2ed5112155feca1e7b03a74eadd1bcac38216
fix #1230 
fix #1226
=> fix: language pack accidentally installed after `WeaselSetup.exe /u`

.github/workflows/commit-ci.yml, .github/workflows/release-ci.yml, WeaselServer/WeaselServer.vcxproj, WeaselSetup/imesetup.cpp, WeaselTSF/WeaselTSF.vcxproj
close #978 
enable windows error report, generate dmp file in `%TEMT%\rime.weasel\`
=> enable windows error report, generate dmp file in %TEMT%\rime.weasel\

WeaselTSF/LanguageBar.cpp, WeaselTSF/WeaselTSF.cpp, WeaselTSF/WeaselTSF.h
follow #1243 make a guardian for WeaselServer.exe
maybe fix #1190
fix #1126 
fix #982
fix #612
fix #505
fix #499
fix #320
close #1203
=> feat: simple guardian for WeaselServer.

WeaselIPC/WeaselClientImpl.cpp
esp when WeaselServer.exe dumping
=> avoid freezing if _SendMessage overtime when ClientImpl::ProcessKeyEvent

WeaselUI/WeaselPanel.cpp
enhancement: semi-hilite with half alpha color of hilite candidate.
fix: semi-hilite hover not clear when moving out of candidate window, after once click select a candidate.
fix #1248
@mirtlebot 
~~known issue: hover not clear in some version of windows.~~
=> hover  issue[skip ci]

WeaselUI/DirectWriteResources.cpp, WeaselUI/FullScreenLayout.cpp, WeaselUI/FullScreenLayout.h, WeaselUI/HorizontalLayout.h, WeaselUI/Layout.cpp, WeaselUI/Layout.h, WeaselUI/StandardLayout.h, WeaselUI/VHorizontalLayout.h, WeaselUI/VerticalLayout.h, WeaselUI/WeaselPanel.cpp, WeaselUI/WeaselPanel.h, include/WeaselUI.h
fix #1224 
@mirtlecn 
DPI= 96(100%)
DPI = 144(150%)
=> fix: UI layout sizes are not DPI aware.

.github/workflows/commit-ci.yml, .github/workflows/release-ci.yml, build.bat
provide rime.pdb for debugging
=> build: update build.bat on building rime, build/cache librime in CI, and provide rime.pdb

WeaselIPC/WeaselClientImpl.cpp, WeaselTSF/KeyEventSink.cpp, WeaselTSF/WeaselTSF.cpp, WeaselTSF/WeaselTSF.h
- Client: All _SendMessage with async task, 2 sec overtime.
- WeaselTSF: _EnsureServerConnected modified to a boolean return function, indicating if server connection is OK.
- WeaselTSF: if server connection is not OK, don't eat the key event, leave it to the client.
=> perf: continually fixes to avoid the client app get freezed when WeaselServer.exe dump or disabled(deploying)

RimeWithWeasel/RimeWithWeasel.cpp
=> walkaround to fix client hanging caused by startup deploying in Server

WeaselSetup/imesetup.cpp, output/install.nsi
ensure all ime/dll deleted when uninstalled by and installer
=> Fix install

WeaselSetup/InstallOptionsDlg.h, WeaselSetup/WeaselSetup.cpp, WeaselSetup/imesetup.cpp
refactor: template to write REG_SZ or REG_DWORD
=> feat: WeaselSetup.exe parameters for enable/disable update checking automatically, /eu to enable, /du to disable

output/install.nsi
Follow up https://github.com/rime/weasel/commit/c599f2e67ab26dac3f77066d4d57d9295092be96
=> fix: silent installation script repeated call

WeaselTSF/WeaselTSF.cpp
=> remove duplicated branch

update/bump-version.ps1
add basetag string parameter `-basetag`
add help switch parameter `-h`
add directory detection
support pwsh in linux(maybe Mac OS too)
fix fileformat modification if not Windows env
=> chore: update update/bump_version.ps1

update/bump-version.ps1, update/bump-version.sh
chore: update update/bump_version.sh [skip ci]
- update releaseNoteLink
- simplify the script with function
- sed edit in binary mode, not to touch the CR-LFs
- add comments
chore: update update/bump-version.ps1 [skip ci]
- add error handling
- simplify the code
- add Shebang for the script
- update releaseNoteLink in xml file
=> Bump version script

WeaselDeployer/SwitcherSettingsDialog.cpp
=> fix(WeaselDeployer): WeaselDeployer will dump if hotkeys is set empty #1549

RimeWithWeasel/RimeWithWeasel.cpp
=> revert: 0d20317 and #1281
